-- require("nvim-tree").setup({
--     filters = {
--         dotfiles = false,
--         git_ignored = false,
--         custom = {
--             ".DS_Store",
--         }
--     },
--     renderer = {
--         icons = {
--             glyphs = {
--                 git = {
--                     ignored = "‡",
--                 },
--             },
--         },
--     },
-- })
--
--
-- vim.keymap.set("n", "<leader>e", ":NvimTreeToggle<CR>")
-- vim.keymap.set("n", "<leader>w", "<C-w><C-w>")
